var unicoder = {
	'dictionary': {
		'parenthesized': {
			'A': '',
			'B': '',
			'C': '',
			'D': '',
			'E': '',
			'F': '',
			'G': '',
			'H': '',
			'I': '',
			'J': '',
			'K': '',
			'L': '',
			'M': '',
			'N': '',
			'O': '',
			'P': '',
			'Q': '',
			'R': '',
			'S': '',
			'T': '',
			'U': '',
			'V': '',
			'W': '',
			'X': '',
			'Y': '',
			'Z': '',
			'0': '',
			'1': '',
			'2': '',
			'3': '',
			'4': '',
			'5': '',
			'6': '',
			'7': '',
			'8': '',
			'9': ''
		},
		'circled': {
			'a': '',
			'b': '',
			'c': '',
			'd': '',
			'e': '',
			'f': '',
			'g': '',
			'h': '',
			'i': '',
			'j': '',
			'k': '',
			'l': '',
			'm': '',
			'n': '',
			'o': '',
			'p': '',
			'q': '',
			'r': '',
			's': '',
			't': '',
			'u': '',
			'v': '',
			'w': '',
			'x': '',
			'y': '',
			'z': '',
			'0': '',
			'1': '',
			'2': '',
			'3': '',
			'4': '',
			'5': '',
			'6': '',
			'7': '',
			'8': '',
			'9': ''
		},
		'negative-circled': {
			'a': '',
			'b': '',
			'c': '',
			'd': '',
			'e': '',
			'f': '',
			'g': '',
			'h': '',
			'i': '',
			'j': '',
			'k': '',
			'l': '',
			'm': '',
			'n': '',
			'o': '',
			'p': '',
			'q': '',
			'r': '',
			's': '',
			't': '',
			'u': '',
			'v': '',
			'w': '',
			'x': '',
			'y': '',
			'z': '',
			'0': '',
			'1': '',
			'2': '',
			'3': '',
			'4': '',
			'5': '',
			'6': '',
			'7': '',
			'8': '',
			'9': ''
		},
		'squared': {
			'a': '',
			'b': '',
			'c': '',
			'd': '',
			'e': '',
			'f': '',
			'g': '',
			'h': '',
			'i': '',
			'j': '',
			'k': '',
			'l': '',
			'm': '',
			'n': '',
			'o': '',
			'p': '',
			'q': '',
			'r': '',
			's': '',
			't': '',
			'u': '',
			'v': '',
			'w': '',
			'x': '',
			'y': '',
			'z': '',
			'0': '',
			'1': '',
			'2': '',
			'3': '',
			'4': '',
			'5': '',
			'6': '',
			'7': '',
			'8': '',
			'9': ''
		},
		'negative-squared': {
			'a': '',
			'b': '',
			'c': '',
			'd': '',
			'e': '',
			'f': '',
			'g': '',
			'h': '',
			'i': '',
			'j': '',
			'k': '',
			'l': '',
			'm': '',
			'n': '',
			'o': '',
			'p': '',
			'q': '',
			'r': '',
			's': '',
			't': '',
			'u': '',
			'v': '',
			'w': '',
			'x': '',
			'y': '',
			'z': '',
			'0': '',
			'1': '',
			'2': '',
			'3': '',
			'4': '',
			'5': '',
			'6': '',
			'7': '',
			'8': '',
			'9': ''
		},
	},

	// Return the text, in the selected unicode format.
	// Hmm, I wonder if this is the most efficient way to do this?
	translate: function( text, type ) {

		// Gather list of letters
		var dictionary = this.dictionary[type];
		var hasCapitals = ( dictionary['a'] && dictionary['A'] );

		if( text.length < Object.keys(dictionary).length ) {
			transitionalTranslate( text, dictionary );
		} else {
			bruteForceTranslate( text, dictionary );
		}
	},

	// Loop through the dictionary, and translate all occurances of items appearing in it.
	// This should be faster for longer text items. (> 30 characters?)
	bruteForceTranslate: function( text, dictionary ) {

	},

	// Loop through the text, and translate if they meet a lookup in the dictionary
	// This should be fastest for shorter text params (< 30 characters?)
	transitionalTranslate: function( text, dictionary ) {

	}
}